server:
  port: 9001

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:postgresql://localhost:5432/novabank_auth
    username: postgres
    password: 655057621




  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/