server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      routes:
        - id: cliente-service
          uri: lb://CLIENTE-SERVICE
          predicates:
            - Path=/api/clientes/**

        - id: cuenta-service
          uri: lb://CUENTA-SERVICE
          predicates:
            - Path=/api/cuentas/**

        - id: operacion-service
          uri: lb://OPERACION-SERVICE
          predicates:
            - Path=/api/operaciones/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/