spring:
  application:
    name: cliente-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/novabank_clientes
    username: postgres
    password: 655057621

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      fail-on-unknown-properties: true